=== saida-ben/Xml-miniProject-bibio/bibliotheque.dtd
<!ELEMENT bibliotheque (livres*, utilisateurs*, parametres)>

<!ELEMENT livres (livre*)>
<!ELEMENT utilisateurs (utilisateur+)>
<!ELEMENT parametres (parametre+)>

<!ELEMENT livre (titre, auteur+, categorie, datePublication, resume, editeur*, emprunt*)>
<!ELEMENT auteur (nom, email)>
<!ELEMENT editeur (nom, adresse+)>
<!ELEMENT adresse (rue, ville, pays)>
<!ELEMENT emprunt (emprunteur, dateEmprunt, dateRetour)>

<!ELEMENT emprunteur (nom, email)>
<!ELEMENT dateEmprunt (#PCDATA)>
<!ELEMENT dateRetour (#PCDATA)>


<!ELEMENT utilisateur (nom, email, role)>
<!ELEMENT parametre (nom, valeur)>

<!ELEMENT titre (#PCDATA)>
<!ELEMENT categorie (#PCDATA)>
<!ELEMENT datePublication (#PCDATA)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT rue (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>
<!ELEMENT role (#PCDATA)>
<!ELEMENT valeur (#PCDATA)>

<!ATTLIST livre num ID #REQUIRED>
<!ATTLIST utilisateur id ID #REQUIRED>

=== saida-ben/Xml-miniProject-bibio/bibliotheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bibliotheque.xsl" ?>
<!-- <!DOCTYPE bibliotheque SYSTEM "bibliotheque.dtd"> -->
<!--<bibliotheque xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="bibliotheque.xsd"> -->
<bibliotheque>
    <livres>
        
        
    <livre num="1"><titre>titre</titre><auteur><nom>SOUKAINA BENZARIYA</nom><email>benzariyasaida@gmail.com</email></auteur><categorie>22</categorie><datePublication>ww</datePublication><resume>fff</resume><editeur><nom>ww</nom><adresse><rue>ss</rue><ville>ss</ville><pays>Maroc</pays></adresse></editeur></livre></livres>
    
  
</bibliotheque>
